// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models.EFModels
{
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int PageViews { get; set; }
        public bool Status { get; set; }
        public string Image { get; set; }
        public DateTime CreatedTime { get; set; }
    }
}