// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models.EFModels
{
    public partial class Orders
    {
        public Orders()
        {
            CustomerServiceMails = new HashSet<CustomerServiceMails>();
            OrderItems = new HashSet<OrderItems>();
        }

        public long Id { get; set; }
        public int UserId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverPhone { get; set; }
        public string TaxIdNum { get; set; }
        public string VehicleNum { get; set; }
        public string Remark { get; set; }
        public DateTime OrderTime { get; set; }
        public int? OrderStatusId { get; set; }
        public decimal TotalAmount { get; set; }
        public string ShippingNumber { get; set; }
        public DateTime? ShippingTime { get; set; }
        public decimal ShippingFee { get; set; }
        public int? ShippingStatusId { get; set; }
        public decimal TotalPayment { get; set; }
        public bool CommentStatus { get; set; }

        public virtual OrderStatuses OrderStatus { get; set; }
        public virtual ShippingStatuses ShippingStatus { get; set; }
        public virtual Users User { get; set; }
        public virtual ICollection<CustomerServiceMails> CustomerServiceMails { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}