// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models.EFModels
{
    public partial class Publishers
    {
        public Publishers()
        {
            Books = new HashSet<Books>();
            PurchaseOrderHistory = new HashSet<PurchaseOrderHistory>();
            PurchaseOrders = new HashSet<PurchaseOrders>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<PurchaseOrderHistory> PurchaseOrderHistory { get; set; }
        public virtual ICollection<PurchaseOrders> PurchaseOrders { get; set; }
    }
}