// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models
{
    public partial class PurchaseOrderHistory
    {
        public int Id { get; set; }
        public int? BookId { get; set; }
        public int? PublisherId { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? Qty { get; set; }
        public string Detail { get; set; }
        public decimal? PurchasePrice { get; set; }

        public virtual Books Book { get; set; }
        public virtual Publishers Publisher { get; set; }
    }
}