// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models.EFModels
{
    public partial class PurchaseOrders
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public decimal PurchasePrice { get; set; }
        public int Qty { get; set; }
        public string Detail { get; set; }
        public DateTime CreatedTime { get; set; }
        public int PublisherId { get; set; }

        public virtual Books Book { get; set; }
        public virtual Publishers Publisher { get; set; }
    }
}