// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models.EFModels
{
    public partial class Roles
    {
        public Roles()
        {
            Employees = new HashSet<Employees>();
            RolePermissions = new HashSet<RolePermissions>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<RolePermissions> RolePermissions { get; set; }
    }
}