// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models
{
    public partial class UserArticleCollections
    {
        public int Id { get; set; }
        public int? UserId { get; set; }
        public int? ArticleId { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual Articles Article { get; set; }
        public virtual Users User { get; set; }
    }
}