// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models
{
    public partial class CustomerServiceMails
    {
        public CustomerServiceMails()
        {
            RepliedMails = new HashSet<RepliedMails>();
        }

        public int Id { get; set; }
        public string UserAccount { get; set; }
        public string Email { get; set; }
        public int ProblemTypeId { get; set; }
        public string ProblemStatement { get; set; }
        public long? OrderId { get; set; }
        public bool IsRead { get; set; }
        public bool IsReplied { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual Orders Order { get; set; }
        public virtual ProblemType ProblemType { get; set; }
        public virtual ICollection<RepliedMails> RepliedMails { get; set; }
    }
}