// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EBookStoreAPI.Models
{
    public partial class Writers
    {
        public Writers()
        {
            Articles = new HashSet<Articles>();
        }

        public int Id { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Profile { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Articles> Articles { get; set; }
    }
}